[package]
name = "padded-number"

description = "Work with numbers containing significant leading zeros"
readme = "README.md"

categories = ["data-structures", "mathematics"]
keywords = ["numerics", "padding"]

authors.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
macros = ["dep:padded-number-macros"]
serde = ["dep:serde"]
unstable-nightly = []

[dependencies]
padded-number-internal.workspace = true
padded-number-macros = { workspace = true, optional = true }

konst.workspace = true

# feature: serde
serde = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
padded-number = { path = ".", features = ["macros", "serde", "unstable-nightly"] }

# feature: serde
serde_json.workspace = true

[lints]
workspace = true

# TEMP: https://github.com/rust-lang/rust/issues/43781
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
