[package]
name = "padded-number"
readme = "README.md"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
macros = ["dep:padded-number-macros"]
serde = ["dep:serde"]

[dependencies]
padded-number-internal.workspace = true
padded-number-macros = { workspace = true, optional = true }

konst.workspace = true

# feature: serde
serde = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
padded-number = { path = ".", features = ["macros", "serde"] }

# feature: serde
serde_json.workspace = true

[lints]
workspace = true
